package org.cc11001100.jfinal.modle.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJob<M extends BaseJob<M>> extends Model<M> implements IBean {

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public M setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
		return (M)this;
	}

	public java.lang.String getCompanyId() {
		return get("company_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setSalaryLow(java.lang.Integer salaryLow) {
		set("salary_low", salaryLow);
		return (M)this;
	}

	public java.lang.Integer getSalaryLow() {
		return get("salary_low");
	}

	public M setSalaryHigh(java.lang.Integer salaryHigh) {
		set("salary_high", salaryHigh);
		return (M)this;
	}

	public java.lang.Integer getSalaryHigh() {
		return get("salary_high");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}

	public java.lang.String getLocation() {
		return get("location");
	}

	public M setWorkExperienceLow(java.lang.Integer workExperienceLow) {
		set("work_experience_low", workExperienceLow);
		return (M)this;
	}

	public java.lang.Integer getWorkExperienceLow() {
		return get("work_experience_low");
	}

	public M setWorkExperienceHigh(java.lang.Integer workExperienceHigh) {
		set("work_experience_high", workExperienceHigh);
		return (M)this;
	}

	public java.lang.Integer getWorkExperienceHigh() {
		return get("work_experience_high");
	}

	public M setDescContent(java.lang.String descContent) {
		set("desc_content", descContent);
		return (M)this;
	}

	public java.lang.String getDescContent() {
		return get("desc_content");
	}

	public M setEducationRequire(java.lang.Integer educationRequire) {
		set("education_require", educationRequire);
		return (M)this;
	}

	public java.lang.Integer getEducationRequire() {
		return get("education_require");
	}

	public M setContact(java.lang.String contact) {
		set("contact", contact);
		return (M)this;
	}

	public java.lang.String getContact() {
		return get("contact");
	}

}
