package org.cc11001100.jfinal.modle.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMsg<M extends BaseMsg<M>> extends Model<M> implements IBean {

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public M setMsgContent(java.lang.String msgContent) {
		set("msg_content", msgContent);
		return (M)this;
	}

	public java.lang.String getMsgContent() {
		return get("msg_content");
	}

	public M setIsHaveRead(java.lang.Integer isHaveRead) {
		set("is_have_read", isHaveRead);
		return (M)this;
	}

	public java.lang.Integer getIsHaveRead() {
		return get("is_have_read");
	}

	public M setHaveReadTime(java.util.Date haveReadTime) {
		set("have_read_time", haveReadTime);
		return (M)this;
	}

	public java.util.Date getHaveReadTime() {
		return get("have_read_time");
	}

}
