package org.cc11001100.jfinal.modle.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseResumeDeliver<M extends BaseResumeDeliver<M>> extends Model<M> implements IBean {

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setResumeId(java.lang.String resumeId) {
		set("resume_id", resumeId);
		return (M)this;
	}

	public java.lang.String getResumeId() {
		return get("resume_id");
	}

	public M setJobId(java.lang.String jobId) {
		set("job_id", jobId);
		return (M)this;
	}

	public java.lang.String getJobId() {
		return get("job_id");
	}

	public M setResult(java.lang.Integer result) {
		set("result", result);
		return (M)this;
	}

	public java.lang.Integer getResult() {
		return get("result");
	}

}
