package org.cc11001100.jfinal.modle;

import java.util.List;

import org.apache.commons.lang.StringUtils;
import org.cc11001100.jfinal.interceptor.AdminInterceptor;
import org.cc11001100.jfinal.modle.base.BaseCompany;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Before(AdminInterceptor.class)
public class Company extends BaseCompany<Company> {
	
	public static final Company dao = new Company().dao();
	
	/**
	 * 获取简短的公司名字
	 * @return
	 */
	public String getBriefName(){
		if(StringUtils.isBlank(getName())){
			return StringUtils.EMPTY;
		}else if(getName().length()<=10){
			return getName();
		}else{
			return getName().substring(0, 7)+"...";
		}
	}
	
	/**
	 * 获取简短的公司名字，可以指定长度
	 * @param length
	 * @return
	 */
	public String getBriefName(int length){
		if(StringUtils.isBlank(getName())){
			return StringUtils.EMPTY;
		}else if(getName().length()<=length){
			return getName();
		}else{
			return getName().substring(0, length-3)+"...";
		}
	}
	
	/**
	 * 获取简短的描述，用于显示描述摘要
	 * @return
	 */
	public String getBriefDescContent(){
		if(StringUtils.isBlank(getDescContent())){
			return StringUtils.EMPTY;
		}else if(getDescContent().length()<=40){
			return getDescContent();
		}else{
			return getDescContent().substring(0, 37)+"...";
		}
	}
	
	/**
	 * 获取简短的描述，用于显示描述摘要，可以指定长度
	 * @param length
	 * @return
	 */
	public String getBriefDescContent(int length){
		if(StringUtils.isBlank(getDescContent())){
			return StringUtils.EMPTY;
		}else if(getDescContent().length()<=length){
			return getDescContent();
		}else{
			return getDescContent().substring(0, length-3)+"...";
		}
	}
	
	/**此公司下累计发布职位数*/
	private Long jobCount;

	public Long getJobCount() {
		String sql="SELECT COUNT(id) FROM t_job WHERE company_id=?";
		jobCount=Db.queryLong(sql, getId());
		return jobCount;
	}

	public Company setJobCount(Long jobCount) {
		this.jobCount = jobCount;
		return this;
	}
	
	/**获取此公司的创建者*/
	private User user;

	public User getUser() {
		if(user==null){
			user=User.dao.findById(getUserId());
		}
		return user;
	}

	public Company setUser(User user) {
		this.user = user;
		return this;
	}
	
	/**此公司下发布的职位*/
	private List<Job> job;

	public List<Job> getJob() {
		String sql="SELECT * FROM t_job WHERE company_id=?";
		job=Job.dao.find(sql, getId());
		return job;
	}

	public Company setJob(List<Job> job) {
		this.job = job;
		return this;
	}
	
	
	
	
}
