package org.cc11001100.jfinal.modle;

import org.cc11001100.jfinal.modle.base.BaseMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Msg extends BaseMsg<Msg> {
	public static final Msg dao = new Msg().dao();
}
