package org.cc11001100.jfinal.modle;

import org.cc11001100.jfinal.modle.base.BaseResumeDeliver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResumeDeliver extends BaseResumeDeliver<ResumeDeliver> {
	
	public static final ResumeDeliver dao = new ResumeDeliver().dao();
	
	/**关联的职位*/
	private Job job;
	
	/**关联到的简历*/
	private Resume resume;

	public Job getJob() {
		if(job==null){
			job=Job.dao.findById(getJobId());
		}
		return job;
	}

	public ResumeDeliver setJob(Job job) {
		this.job = job;
		return this;
	}

	public Resume getResume() {
		if(resume==null){
			resume=Resume.dao.findById(getResumeId());
		}
		return resume;
	}

	public ResumeDeliver setResume(Resume resume) {
		this.resume = resume;
		return this;
	}
	
	/**
	 * 投递结果
	 * 
	 * @author CC11001100
	 *
	 */
	public static class Resule{
		
		/**未处理*/
		public static final Integer UNPROCESS=0;
		
		/**不合适*/
		public static final Integer REFUSE=1;
		
		/**邀请面试*/
		public static final Integer INTERVIEW_INVITE=2;
		
	}
	
	/**
	 * 获得可读的格式
	 * @return
	 */
	public String getPlainStatus(){
		switch(getResult()){
			case 0:
				return "未处理";
			case 1:
				return "不合适";
			case 2:
				return "邀请面试";
			default:
				return "未处理";
					
		}
	}
	
}
